import { Account } from '@/types/account';

export const mockAccounts: Account[] = [
  {
    id: '1',
    name: 'TechCorp Solutions',
    email: 'contact@techcorp.com',
    phone: '+1-555-0123',
    company: 'TechCorp Solutions Inc.',
    industry: 'Technology',
    location: 'San Francisco, CA',
    website: 'https://techcorp.com',
    description: 'Leading provider of enterprise software solutions',
    foundedYear: 2010,
    employeeCount: 250,
    revenue: 50000000,
    socialMedia: {
      linkedin: 'https://linkedin.com/company/techcorp',
      twitter: 'https://twitter.com/techcorp',
    },
    tags: ['enterprise', 'SaaS', 'B2B'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-10'),
    researchNotes: 'Key player in cloud computing space, strong market position',
    status: 'prospect',
    value: 'high',
  },
  {
    id: '2',
    name: 'Global Marketing Agency',
    email: 'info@globalmarketing.com',
    phone: '+1-555-0124',
    company: 'Global Marketing LLC',
    industry: 'Marketing & Advertising',
    location: 'New York, NY',
    website: 'https://globalmarketing.com',
    description: 'Full-service digital marketing agency',
    foundedYear: 2015,
    employeeCount: 50,
    revenue: 8000000,
    socialMedia: {
      linkedin: 'https://linkedin.com/company/globalmarketing',
      instagram: 'https://instagram.com/globalmarketing',
    },
    tags: ['marketing', 'digital', 'agency'],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-08'),
    researchNotes: 'Growing agency, good fit for partnership opportunities',
    status: 'active',
    value: 'medium',
  },
  {
    id: '3',
    name: 'Innovate Finance',
    email: 'hello@innovatefinance.com',
    phone: '+1-555-0125',
    company: 'Innovate Finance Corp',
    industry: 'Financial Technology',
    location: 'London, UK',
    website: 'https://innovatefinance.com',
    description: 'Fintech startup revolutionizing personal banking',
    foundedYear: 2020,
    employeeCount: 30,
    revenue: 3000000,
    socialMedia: {
      linkedin: 'https://linkedin.com/company/innovatefinance',
      twitter: 'https://twitter.com/innovatefinance',
    },
    tags: ['fintech', 'startup', 'banking'],
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-03-09'),
    researchNotes: 'Emerging fintech with innovative products',
    status: 'prospect',
    value: 'high',
  },
];

export const industries = [
  'Technology',
  'Financial Technology',
  'Marketing & Advertising',
  'Healthcare',
  'Manufacturing',
  'Retail',
  'Education',
  'Real Estate',
  'Consulting',
  'Other',
];

export const locations = [
  'San Francisco, CA',
  'New York, NY',
  'London, UK',
  'Tokyo, Japan',
  'Berlin, Germany',
  'Toronto, Canada',
  'Sydney, Australia',
  'Other',
];
